# html lang
language: en
keywords: hexo theme,ZXD
# main menu navigation

#所有评论的总开关
commets: true

#如果需要开启有言，输入您的有言ID
youyanid: 2123180

menu:
  home: /
  archives: archives/
  tags: tags/
  # categories: categories/
  about: about/
  # 如果你想自定义页面，可以在这里加上你的path，然后hexo new page
  # custom: custom/

# Miscelaneous
favicon: favicon.ico

# author's image
avatar: /img/avatar.png


#Contact in sidebar
sidebar:
  GitHub:
   href: https://github.com/zhuxudong/zhuxudong.github.io
   icon: github
  源码:
   href: https://github.com/zhuxudong/hexo-ZXD
   icon: github

# the amount of latest posts you want to show
latest_amount: 5
# if you want close the 'theme by' in footer ,you can choose the copyright to the false;
copyright: ture

#if you want open the updated timemeta in post,you can change it to 'true'
updated: false


#the file rootpath
img: /img
js: /js
css: /css